<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>drone_teleop</name>
  <version>0.1.0</version>
  <description>
    Launch files and bridge configuration for manual drone teleoperation
    in LOTUSim. Bridges Gazebo Harmonic topics to ROS 2 and starts
    keyboard or joystick control for the x500 drone.
  </description>
  <maintainer email="theagechhai@gmail.com">gechhai</maintainer>
  <license>EPL-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>teleop_twist_keyboard</exec_depend>
  <exec_depend>teleop_twist_joy</exec_depend>
  <exec_depend>joy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
